export const PERFORMANCE_PROFILE_NAMES = Object.freeze(["performance", "balanced", "cinematic", "server"]);

export const PERFORMANCE_PROFILES = Object.freeze({
  performance: {
    name: "performance",
    lodImpostors: 12,
    lodPlacementsPerMinute: 4,
    cityActiveRadius: 64,
    terrainProfile: "performance",
    terrainDecorators: "low",
    particleScale: 0.25,
    guardsPerCity: 4,
    clumpsIntervalTicks: 20,
    simulationRecommendation: "4 chunks",
    maxBlockOpsPerTick: 64,
    maxEntityChecksPerTick: 32,
    maxStructurePlacementsPerTick: 1,
    itemCleanupIntervalTicks: 1200,
    entityCleanupIntervalTicks: 400,
    maxHostilesNearCity: 18
  },
  balanced: {
    name: "balanced",
    lodImpostors: 32,
    lodPlacementsPerMinute: 10,
    cityActiveRadius: 96,
    terrainProfile: "balanced",
    terrainDecorators: "normal",
    particleScale: 0.5,
    guardsPerCity: 8,
    clumpsIntervalTicks: 20,
    simulationRecommendation: "4-6 chunks",
    maxBlockOpsPerTick: 64,
    maxEntityChecksPerTick: 32,
    maxStructurePlacementsPerTick: 1,
    itemCleanupIntervalTicks: 1200,
    entityCleanupIntervalTicks: 360,
    maxHostilesNearCity: 28
  },
  cinematic: {
    name: "cinematic",
    lodImpostors: 64,
    lodPlacementsPerMinute: 18,
    cityActiveRadius: 128,
    terrainProfile: "cinematic",
    terrainDecorators: "high",
    particleScale: 1.0,
    guardsPerCity: 12,
    clumpsIntervalTicks: 20,
    simulationRecommendation: "6 chunks, strong device/server",
    maxBlockOpsPerTick: 64,
    maxEntityChecksPerTick: 32,
    maxStructurePlacementsPerTick: 1,
    itemCleanupIntervalTicks: 1000,
    entityCleanupIntervalTicks: 300,
    maxHostilesNearCity: 40
  },
  server: {
    name: "server",
    lodImpostors: 8,
    lodPlacementsPerMinute: 4,
    cityActiveRadius: 64,
    terrainProfile: "performance",
    terrainDecorators: "very_low",
    particleScale: 0.1,
    guardsPerCity: 4,
    clumpsIntervalTicks: 20,
    simulationRecommendation: "4 chunks",
    maxBlockOpsPerTick: 64,
    maxEntityChecksPerTick: 24,
    maxStructurePlacementsPerTick: 1,
    itemCleanupIntervalTicks: 900,
    entityCleanupIntervalTicks: 300,
    maxHostilesNearCity: 14
  }
});
